apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://fx-prometheus:9090
    isDefault: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://fx-qual-jaeger:16686

  - name: Loki
    type: loki
    access: proxy
    url: http://fx-loki:3100
