server:
  port: 8080

spring:
  application:
    name: fxqual-engine

integrations:
  customer:
    base-url: http://localhost:8081/api/customer
  product:
    base-url: http://localhost:8081/api/product
  promo:
    base-url: http://localhost:8081/api/promo
  market-data:
    base-url: http://localhost:8081/api/market

logging:
  level:
    root: INFO
    io.opentelemetry: INFO
    org.springframework.boot.actuate.autoconfigure.opentelemetry: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  metrics:
    tags:
      service: fx-qual-engine
