server:
  port: 8080

spring:
  application:
    name: FX-Qual-Engine

management:
  observations:
    enable-log-correlation: false

logging:
  pattern:
    level: "%5p [traceId:%X{traceId} spanId:%X{spanId}]"

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

  enable-hateoas: false
  enable-hal: false
  data-rest:
    enabled: false