server:
  port: 8080

spring:
  application:
    name: fxqual-engine

integrations:
  customer:
    base-url: http://localhost:8081/api/customer
  product:
    base-url: http://localhost:8081/api/product
  promo:
    base-url: http://localhost:8081/api/promo
  market-data:
    base-url: http://localhost:8081/api/market

logging:
  level:
    root: DEBUG
    io.opentelemetry: DEBUG
    org.springframework.boot.actuate.autoconfigure.opentelemetry: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    export:
      enabled: true
      otlp:
        endpoint: http://localhost:24318/v1/traces

  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:24318/v1/metrics
