

services:
  local-prometheus:
    image: prom/prometheus:v2.53.0
    container_name: local-prometheus
    ports:
      - "9090:9090"
    volumes:
      - fxqual-prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fxqual-local-net

volumes:
  fxqual-prometheus-data:

networks:
  fxqual-local-net:
    driver: bridge
