services:

  prometheus:
    image: prom/prometheus:latest
    container_name: fxqual-prometheus
    restart: always
    networks:
      - fxqual-local-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./recording_rules.yml:/etc/prometheus/recording_rules.yml
      - fxqual-prometheus-data:/prometheus

volumes:
  fxqual-prometheus-data:

networks:
  fxqual-local-net:
    driver: bridge
